services:
  - type: web
    name: zain-frontend
    runtime: node
    repo: https://github.com/marwanhubeg/zain-real-estate
    branch: main
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://zain-backend.onrender.com/api
    domains:
      - zain-real-estate.onrender.com
